services:
  nginx:
    image: nginx:1.28.0-alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"  # expose HTTPS
    depends_on:
      - threesixty-admin
      - threesixty-discovery
      - scim-server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs/tls.crt:/etc/nginx/certs/tls.crt:ro
      - ./nginx/certs/tls.key:/etc/nginx/certs/tls.key:ro
    restart: unless-stopped
    networks:
      - threesixty

  threesixty-admin:
    image: 782396859527.dkr.ecr.ap-southeast-2.amazonaws.com/objective3sixty:5.0.2-RC1
    container_name: threesixty-admin
    env_file:
      - ./.env.admin
    environment:
      SSL_ENABLED: false
    depends_on:
      - mongo
    restart: on-failure:5
    networks:
      - threesixty
    #volumes:
    #  - ../my-data:/usr/local/tomcat/localMount:rw

  threesixty-discovery:
    image: 782396859527.dkr.ecr.ap-southeast-2.amazonaws.com/objective3sixtydiscovery:5.0.2-RC1
    container_name: threesixty-discovery
    env_file:
      - ./.env.discovery
    environment:
      SSL_ENABLED: false
    depends_on:
      - mongo
      - threesixty-admin
    restart: on-failure:5
    networks:
      - threesixty
    #volumes:
    #- ./vault-agent/.vault-token:/vault/.vault-token:ro

  mongo:
    image: mongo:8.0.9
    container_name: mongo
    ports:
      - "27017:27017"
    env_file:
      - ./.env.mongo
    volumes:
      - mongo_data:/data/db
      - ./mongodb/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    restart: unless-stopped
    networks:
      - threesixty

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    restart: unless-stopped
    networks:
      - threesixty

  # Declarative Agent
  oi-rag:
    image: 782396859527.dkr.ecr.ap-southeast-2.amazonaws.com/objectiveoirag:5.0.1-RC3
    container_name: oi-rag
    env_file:
      - ./.env.oirag
    volumes:
      - ./logs:/oi-rag-logs
    depends_on:
      - opensearch
      - ollama
    restart: unless-stopped
    networks:
      - threesixty

  ollama:
    image: ollama/ollama:0.7.0
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: [ "bash", "-c" ]
    command: >
      "ollama serve & sleep 5 && ollama pull mxbai-embed-large && wait"
    restart: unless-stopped
    networks:
      - threesixty

  opensearch:
    image: opensearchproject/opensearch:2.4.1
    container_name: opensearch
    environment:
      http.host: 0.0.0.0
      network.host: 0.0.0.0
      transport.host: 127.0.0.1
      discovery.type: single-node
      compatibility.override_main_response_version: true
      bootstrap.memory_lock: true # Disable JVM heap memory swapping
      OPENSEARCH_JAVA_OPTS: "-Xms2g -Xmx2g"
    volumes:
      - opensearch_data:/usr/share/opensearch/data:rw
    restart: unless-stopped
    networks:
      - threesixty

  opensearch-dashboard:
    image: opensearchproject/opensearch-dashboards:2.4.1
    container_name: opensearch-dashboard
    ports:
      - "15601:5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
    depends_on:
      - opensearch
    restart: unless-stopped
    networks:
      - threesixty

  # SCIM user provisioning
  rabbitmq:
    image: rabbitmq:4.1-management
    container_name: rabbitmq
    env_file:
      - ./.env.rabbitmq
    ports:
      #   - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
    networks:
      - threesixty
  
  scim-server:
    image: 782396859527.dkr.ecr.ap-southeast-2.amazonaws.com/objectivescimserver:1.0.5
    container_name: scim-server
    env_file:
      - ./.env.scim
    depends_on:
      - mongo
      - rabbitmq
    restart: on-failure:5
    networks:
      - threesixty

volumes:
  opensearch_data:
  mongo_data:
    name: docker_mongo_data
  es_data:
  ollama_data:

networks:
  threesixty:
    name: threesixty
    driver: bridge
