version: "3.8"

services:
  remote-agent-oi-rag:
    image: ghcr.io/objective-corporation/3sixty/remote-agent-oi-rag:5.0.0
    container_name: remote-agent-oi-rag
    env_file:
      - ./.env.oi-agent
    networks:
      - threesixty

networks:
  threesixty:
    name: threesixty
    driver: bridge
