apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hybridsearch.fullname" . }}-oirag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "hybridsearch.fullname" . }}-oirag
  template:
    metadata:
      labels:
        app: {{ include "hybridsearch.fullname" . }}-oirag
    spec:
      imagePullSecrets:
        - name: ecr-registry-secret
      containers:
        - name: oi-rag
          image: "{{ .Values.oirag.image.repository }}:{{ .Values.oirag.image.tag }}"
          imagePullPolicy: {{ .Values.oirag.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "hybridsearch.fullname" . }}-oirag-config
          ports:
            - name: http
              containerPort: {{ .Values.oirag.service.port }}
          volumeMounts:
            - name: logs
              mountPath: {{ .Values.oirag.logs.emptyDir | default "/oi-rag-logs" }}
      volumes:
        - name: logs
          emptyDir: {}
