apiVersion: v1
kind: Service
metadata:
  name: {{ include "hybridsearch.fullname" . }}-oirag
spec:
  type: {{ .Values.oirag.service.type }}
  selector:
    app: {{ include "hybridsearch.fullname" . }}-oirag
  ports:
    - name: http
      port: {{ .Values.oirag.service.port }}
      targetPort: {{ .Values.oirag.service.port }}
