replicaCount: 1

image:
  repository: mongo
  tag: "8.0.11"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 27017

persistence:
  enabled: true
  storageClass: local-path
  accessMode: ReadWriteOnce
  size: 5Gi

init:
  enabled: true
  database: dbtest
  scimDatabase: scim-database
  rootUsername: dbuser
  rootPassword: dbpassword
