apiVersion: v1
kind: Service
metadata:
  name: {{ include "elasticsearch.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "elasticsearch.fullname" . }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.httpPort }}
    - name: transport
      port: {{ .Values.service.transportPort }}
      targetPort: {{ .Values.service.transportPort }}
