apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opensearch.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "opensearch.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "opensearch.fullname" . }}
    spec:
      containers:
        - name: opensearch
          image: "{{ .Values.image.opensearch.repository }}:{{ .Values.image.opensearch.tag }}"
          imagePullPolicy: {{ .Values.image.opensearch.pullPolicy }}
          args:
{{ toYaml .Values.cluster.settings | indent 12 }}
          env:
            - name: OPENSEARCH_JAVA_OPTS
              value: "{{ .Values.javaOpts }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.httpPort }}
            - name: transport
              containerPort: {{ .Values.service.transportPort }}
          volumeMounts:
            - name: data
              mountPath: /usr/share/opensearch/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "opensearch.fullname" . }}-data
