{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "opensearch.fullname" . }}-data
  annotations:
    helm.sh/resource-policy: keep
  labels:
    {{- include "opensearch.labels" . | nindent 4 }}
    app.kubernetes.io/component: search
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
