apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "threesixty.fullname" . }}-admin-config
data:
  {{- if contains "afs" .Values.image.tag }}
  APP_URI: "/afs-admin"
  {{- else }}
  APP_URI: "/3sixty-admin"
  {{- end }}
  {{- if .Values.scim.enabled }}
  RABBITMQ_HOST: "{{ .Values.env.admin.RABBITMQ_HOST }}"
  {{- else }}
  RABBITMQ_HOST: ""
  {{- end }}
  RABBITMQ_QUEUE: "{{ .Values.env.admin.RABBITMQ_QUEUE }}"
  GRPC_SERVER_START: "{{ .Values.env.admin.GRPC_SERVER_START }}"
  GRPC_SERVER_SSL: "{{ .Values.env.admin.GRPC_SERVER_SSL }}"
  GLOBAL_ORG: "{{ .Values.env.admin.GLOBAL_ORG }}"
