apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "threesixty.fullname" . }}-admin
  labels:
    app: {{ include "threesixty.fullname" . }}-admin
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "threesixty.fullname" . }}-admin
  template:
    metadata:
      labels:
        app: {{ include "threesixty.fullname" . }}-admin
    spec:
      imagePullSecrets:
        - name: ecr-registry-secret
      containers:
        - name: threesixty-admin
          image: "{{ .Values.image.registry }}/{{ .Values.image.adminRepo }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.adminPort }}
          envFrom:
            - configMapRef:
                name: {{ include "threesixty.fullname" . }}-admin-config
            - secretRef:
                name: {{ include "threesixty.fullname" . }}-admin-secret
