apiVersion: v1
kind: Secret
metadata:
  name: {{ include "threesixty.fullname" . }}-admin-secret
type: Opaque
stringData:
  MONGODB_URI: "mongodb://{{ .Values.mongodb.username }}:{{ .Values.mongodb.password }}@{{ include "threesixty.fullname" . }}-mongo:27017/{{ .Values.mongodb.database }}"
  RABBITMQ_USERNAME: {{ .Values.rabbitmq.username | quote }}
  RABBITMQ_PASSWORD: {{ .Values.rabbitmq.password | quote }}
  SCIM_TOKEN_URL: "http://{{ include "threesixty.fullname" . }}-scim-server:{{ .Values.scim.config.serverPort }}/scim/v2/token"
  SCIM_USERNAME: {{ .Values.scim.credentials.username | quote }}
  SCIM_PASSWORD: {{ .Values.scim.credentials.password | quote }} 