apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "threesixty.fullname" . }}-discovery-config
  labels:
    app.kubernetes.io/name: {{ include "threesixty.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  APP_URI: {{ if contains "afs" .Values.image.tag }}"http://{{ printf "%s-admin" .Release.Name }}:{{ .Values.service.adminPort }}/afs-admin"{{ else }}"http://{{ printf "%s-admin" .Release.Name }}:{{ .Values.service.adminPort }}/3sixty-admin"{{ end }}
  OAUTH2_ENABLED: {{ .Values.env.discovery.OAUTH2_ENABLED | quote }}
