apiVersion: v1
kind: Secret
metadata:
  name: {{ include "threesixty.fullname" . }}-discovery-secret
type: Opaque
stringData:
  CLIENT_ID: {{ .Values.oauth2.clientId | quote }}
  TENANT_ID: {{ .Values.oauth2.tenantId | quote }}
  CLIENT_SECRET: {{ .Values.oauth2.clientSecret | quote }} 