# templates/discovery-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "threesixty.fullname" . }}-discovery
  labels:
    app: {{ include "threesixty.fullname" . }}-discovery
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "threesixty.fullname" . }}-discovery
  template:
    metadata:
      labels:
        app: {{ include "threesixty.fullname" . }}-discovery
    spec:
      imagePullSecrets:
        - name: ecr-registry-secret
      containers:
        - name: threesixty-discovery
          image: "{{ .Values.image.registry }}/{{ .Values.image.discoveryRepo }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.discoveryPort }}
          envFrom:
            - configMapRef:
                name: {{ include "threesixty.fullname" . }}-discovery-config
            - secretRef:
                name: {{ include "threesixty.fullname" . }}-discovery-secret
