# charts/threesixty/templates/discovery-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "threesixty.fullname" . }}-discovery-config
data:
  {{- if contains "afs" .Values.image.tag }}
  APP_URI: "http://{{ printf "%s-admin" .Release.Name }}:{{ .Values.service.adminPort }}/afs-admin"
  {{- else }}
  APP_URI: "http://{{ printf "%s-admin" .Release.Name }}:{{ .Values.service.adminPort }}/3sixty-admin"
  {{- end }}
  OAUTH2_ENABLED: "{{ .Values.env.discovery.OAUTH2_ENABLED }}"
