apiVersion: v1
kind: Secret
metadata:
  name: {{ include "threesixty.fullname" . }}-mongodb-secret
type: Opaque
stringData:
  MONGODB_USERNAME: {{ .Values.mongodb.username | quote }}
  MONGODB_PASSWORD: {{ .Values.mongodb.password | quote }}
  MONGODB_DATABASE: {{ .Values.mongodb.database | quote }}
  MONGODB_SCIM_DATABASE: {{ .Values.mongodb.scimDatabase | quote }} 