{{- if .Values.scim.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "threesixty.fullname" . }}-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "threesixty.fullname" . }}-rabbitmq
  template:
    metadata:
      labels:
        app: {{ include "threesixty.fullname" . }}-rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: "{{ .Values.rabbitmq.image.repository }}:{{ .Values.rabbitmq.image.tag }}"
          imagePullPolicy: {{ .Values.rabbitmq.image.pullPolicy }}
          ports:
            - name: amqp
              containerPort: {{ .Values.rabbitmq.service.ports.amqp }}
            - name: management
              containerPort: {{ .Values.rabbitmq.service.ports.management }}
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: {{ .Values.env.rabbitmq.RABBITMQ_DEFAULT_USER | quote }}
            - name: RABBITMQ_DEFAULT_PASS
              value: {{ .Values.env.rabbitmq.RABBITMQ_DEFAULT_PASS | quote }}
{{- end }}