{{- if .Values.scim.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "threesixty.fullname" . }}-scim-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "threesixty.fullname" . }}-scim-server
  template:
    metadata:
      labels:
        app: {{ include "threesixty.fullname" . }}-scim-server
    spec:
      imagePullSecrets:
        - name: ecr-registry-secret
      containers:
        - name: scim-server
          image: "{{ .Values.scim.image.repository }}:{{ .Values.scim.image.tag }}"
          imagePullPolicy: {{ .Values.scim.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.scim.config.serverPort }}
          envFrom:
            - configMapRef:
                name: {{ include "threesixty.fullname" . }}-scim-config
            - secretRef:
                name: {{ include "threesixty.fullname" . }}-scim-secret
{{- end }}
