apiVersion: v1
kind: Service
metadata:
  name: {{ include "threesixty.fullname" . }}-admin
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "threesixty.fullname" . }}-admin
  ports:
    - name: {{ .Values.ports.http.name }}
      protocol: TCP
      port: {{ .Values.ports.http.servicePort }}
      targetPort: {{ .Values.ports.http.containerPort }}
    - name: {{ .Values.ports.grpc.name }}
      protocol: TCP
      port: {{ .Values.ports.grpc.servicePort }}
      targetPort: {{ .Values.ports.grpc.containerPort }}      
