apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mongo.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mongo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mongo.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mongo.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: mongo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: data
              mountPath: /data/db
            {{- if .Values.init.enabled }}
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d/init-mongo.sh
              subPath: init-mongo.sh
            {{- end }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "mongo.fullname" . }}-pvc
        {{- if .Values.init.enabled }}
        - name: init-script
          configMap:
            name: {{ include "mongo.fullname" . }}-init-script
            defaultMode: 0755
        {{- end }}
